<?php

namespace modava\log\controllers;

use modava\log\components\MyLogController;
use modava\log\models\search\Voip24hLogSearch;

class Voip24hLogController extends MyLogController
{
    public function init()
    {
        /* If don't have class CallCenter => redirect to index */
        if (!class_exists('\modava\voip24h\CallCenter')) return $this->redirect(['/site/index']);
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function actionIndex()
    {
//        echo '<pre>';
//        var_dump(\Yii::$app->request->queryParams);die;
        $searchModel = new Voip24hLogSearch();
        $dataProvider = $searchModel->search(\Yii::$app->request->queryParams);
        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider
        ]);
    }
}