<?php
namespace modava\log\components;

use backend\components\MyController;

class MyLogController extends MyController
{
    public function behaviors()
    {
        return parent::behaviors(); // TODO: Change the autogenerated stub
    }
}
